### ISSUE TITLE
missing SVLEN field

### ISSUE THREAD

**Issue by abrusell** [bioinfo-chru-strasbourg/vcf2circos#24]
Trying vcf2circos on my vcf produced with delly v1.1.6,
it complains on missing SVLEN field:
`ERROR missing SVLEN annotation for record  Record(CHROM=chr1, POS=1207339, REF=G, ALT=[<DEL>])`
The vcf has SVLEN field only on INS
Does it have to be present on every call?
Can I workaround this?
Thanks

**Comment by JbaptisteLam** [comment]
Hi,
To get structural variant length between breakend the SVLEN information should be present in INFO field for every variant otherwise it can't infer it
It's also possible that you have an other information to obtain the sv length like END or SV_end which is stack as an integer in INFO field, change it to SVLEN,
You can send me the vcf if you want jean-baptiste.lamouche@chru-strasbourg.fr

Best,
